export const newestList = [
  {
    id: 1,
    no_document: '09/DV/01/2023',
    title: 'Lorem ipsum dolor sit amet',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    signeeId: 1,
    signee: 'John Doe',
    requesteeId: 4,
    requestee: 'Manuel Neuer',
    date: '17/12/2023',
    status: 'Pending',
  },
  {
    id: 2,
    no_document: '02/XF/01/2023',
    title: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    signeeId: 2,
    signee: 'Mark Zuckerberg',
    requesteeId: 1,
    requestee: 'John Doe',
    date: '17/12/2023',
    status: 'Done',
  },
  {
    id: 3,
    no_document: '01/AO/01/2023',
    title: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    signeeId: 1,
    signee: 'John Doe',
    requesteeId: 3,
    requestee: 'Gaming Chair nigger nigger nigger nigger nigger',
    date: '17/12/2023',
    status: 'Done',
  },
  {
    id: 4,
    no_document: '02/XF/01/2023',
    title: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    signeeId: 2,
    signee: 'Mark Zuckerberg',
    requesteeId: 1,
    requestee: 'John Doe',
    date: '17/12/2023',
    status: 'Rejected',
  },
  {
    id: 5,
    no_document: '02/XF/01/2023',
    title: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    signeeId: 2,
    signee: 'Mark Zuckerberg',
    requesteeId: 1,
    requestee: 'John Doe',
    date: '17/12/2023',
    status: 'Pending',
  },
  {
    id: 6,
    no_document: '01/AO/01/2023',
    title: 'Lorem ipsum dolor sit amet',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    signeeId: 1,
    signee: 'John Doe',
    requesteeId: 3,
    requestee: 'Gaming Chair nigger nigger nigger nigger nigger',
    date: '17/12/2023',
    status: 'Rejected',
  },
];
